listen_addresses = '*'
logging_collector = on
log_destination = 'stderr,jsonlog'
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = 1d
log_truncate_on_rotation = on
timezone = 'UTC'

