from __future__ import annotations

from typing import Any, Protocol


class ExchangeAdapter(Protocol):
    exchange_id: str

    def resolve_symbol(self, raw_symbol: str) -> str: ...

    def resolve_cached_symbol(self, raw_symbol: str) -> str | None: ...

    def fetch_instruments(self, symbol: str | None = None) -> list[dict[str, Any]]: ...

    def fetch_prices(self, symbols: list[str] | tuple[str, ...] | None = None) -> list[dict[str, Any]]: ...

    def fetch_order_book(self, symbol: str) -> dict[str, Any]: ...

    def market(self, symbol: str) -> dict[str, Any]: ...

    def close(self) -> None: ...
